function createItems() {
  //First greek elements slot.
  createEle("gElements1", "gre1t1", 1, "images/blank.png", 0, "greek", "true");
  createEle("gElements1", "gre1t2", 1, "images/greek/fire.png", 1, "greek", "true");
  createEle("gElements1", "gre1t3", 1, "images/greek/water.png", 2, "greek", "true");
  createEle("gElements1", "gre1t4", 1, "images/greek/earth.png", 3, "greek", "true");
  createEle("gElements1", "gre1t5", 1, "images/greek/air.png", 4, "greek", "true");
  createBre("gElements1");
  createEle("gElements1", "gre1t6", 1, "images/greek/steam.png", 5, "greek", "false");

  //Second greek elements slot.
  createEle("gElements2", "gre2t1", 2, "images/blank.png", 0, "greek", "true");
  createEle("gElements2", "gre2t2", 2, "images/greek/fire.png", 1, "greek", "true");
  createEle("gElements2", "gre2t3", 2, "images/greek/water.png", 2, "greek", "true");
  createEle("gElements2", "gre2t4", 2, "images/greek/earth.png", 3, "greek", "true");
  createEle("gElements2", "gre2t5", 2, "images/greek/air.png", 4, "greek", "true");
  createBre("gElements2");
  createEle("gElements2", "gre2t6", 2, "images/greek/steam.png", 5, "greek", "false");

  //First american elements slot.
  createEle("aElements1", "ame1t1", 3, "images/blank.png", 0, "greek", "true");
  createEle("aElements1", "ame1t2", 3, "images/american/hydrogen.png", 1, "american", "false");
  createEle("aElements1", "ame1t3", 3, "images/american/helium.png", 2, "american", "false");
  createEle("aElements1", "ame1t4", 3, "images/american/lithium.png", 3, "american", "false");
  createEle("aElements1", "ame1t5", 3, "images/american/beryllium.png", 4, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t6", 3, "images/american/boron.png", 5, "american", "false");
  createEle("aElements1", "ame1t7", 3, "images/american/carbon.png", 6, "american", "false");
  createEle("aElements1", "ame1t8", 3, "images/american/nitrogen.png", 7, "american", "false");
  createEle("aElements1", "ame1t9", 3, "images/american/oxygen.png", 8, "american", "false");
  createEle("aElements1", "ame1t10", 3, "images/american/fluorine.png", 9, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t11", 3, "images/american/neon.png", 10, "american", "false");
  createEle("aElements1", "ame1t12", 3, "images/american/sodium.png", 11, "american", "false");
  createEle("aElements1", "ame1t13", 3, "images/american/magnesium.png", 12, "american", "false");
  createEle("aElements1", "ame1t14", 3, "images/american/aluminium.png", 13, "american", "false");
  createEle("aElements1", "ame1t15", 3, "images/american/silocon.png", 14, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t16", 3, "images/american/phosphorus.png", 15, "american", "false");
  createEle("aElements1", "ame1t17", 3, "images/american/sulfur.png", 16, "american", "false");
  createEle("aElements1", "ame1t18", 3, "images/american/chlorine.png", 17, "american", "false");
  createEle("aElements1", "ame1t19", 3, "images/american/argon.png", 18, "american", "false");
  createEle("aElements1", "ame1t20", 3, "images/american/potassium.png", 19, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t21", 3, "images/american/calcium.png", 20, "american", "false");
  createEle("aElements1", "ame1t22", 3, "images/american/scandium.png", 21, "american", "false");
  createEle("aElements1", "ame1t23", 3, "images/american/titanium.png", 22, "american", "false");
  createEle("aElements1", "ame1t24", 3, "images/american/vanadium.png", 23, "american", "false");
  createEle("aElements1", "ame1t25", 3, "images/american/chromium.png", 24, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t26", 3, "images/american/manganese.png", 25, "american", "false");
  createEle("aElements1", "ame1t27", 3, "images/american/iron.png", 26, "american", "false");
  createEle("aElements1", "ame1t28", 3, "images/american/cobalt.png", 27, "american", "false");
  createEle("aElements1", "ame1t29", 3, "images/american/nickel.png", 28, "american", "false");
  createEle("aElements1", "ame1t30", 3, "images/american/copper.png", 29, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t31", 3, "images/american/zinc.png", 30, "american", "false");
  createEle("aElements1", "ame1t32", 3, "images/american/gallium.png", 31, "american", "false");
  createEle("aElements1", "ame1t33", 3, "images/american/germanium.png", 32, "american", "false");
  createEle("aElements1", "ame1t34", 3, "images/american/arsenic.png", 33, "american", "false");
  createEle("aElements1", "ame1t35", 3, "images/american/selenium.png", 34, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t36", 3, "images/american/bromine.png", 35, "american", "false");
  createEle("aElements1", "ame1t37", 3, "images/american/krypton.png", 36, "american", "false");
  createEle("aElements1", "ame1t38", 3, "images/american/rubidium.png", 37, "american", "false");
  createEle("aElements1", "ame1t39", 3, "images/american/strontium.png", 38, "american", "false");
  createEle("aElements1", "ame1t40", 3, "images/american/yttrium.png", 39, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t41", 3, "images/american/zirconium.png", 40, "american", "false");
  createEle("aElements1", "ame1t42", 3, "images/american/niobium.png", 41, "american", "false");
  createEle("aElements1", "ame1t43", 3, "images/american/molybdenium.png", 42, "american", "false");
  createEle("aElements1", "ame1t44", 3, "images/american/technetium.png", 43, "american", "false");
  createEle("aElements1", "ame1t45", 3, "images/american/ruthenium.png", 44, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t46", 3, "images/american/rhodium.png", 45, "american", "false");
  createEle("aElements1", "ame1t47", 3, "images/american/palladium.png", 46, "american", "false");
  createEle("aElements1", "ame1t48", 3, "images/american/silver.png", 47, "american", "false");
  createEle("aElements1", "ame1t49", 3, "images/american/cadmium.png", 48, "american", "false");
  createEle("aElements1", "ame1t50", 3, "images/american/indium.png", 49, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t51", 3, "images/american/tin.png", 50, "american", "false");
  createEle("aElements1", "ame1t52", 3, "images/american/antimony.png", 51, "american", "false");
  createEle("aElements1", "ame1t53", 3, "images/american/tellurium.png", 52, "american", "false");
  createEle("aElements1", "ame1t54", 3, "images/american/iodine.png", 53, "american", "false");
  createEle("aElements1", "ame1t55", 3, "images/american/xenon.png", 54, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t56", 3, "images/american/caesium.png", 55, "american", "false");
  createEle("aElements1", "ame1t57", 3, "images/american/barium.png", 56, "american", "false");
  createEle("aElements1", "ame1t58", 3, "images/american/lanthanium.png", 57, "american", "false");
  createEle("aElements1", "ame1t59", 3, "images/american/cerium.png", 58, "american", "false");
  createEle("aElements1", "ame1t60", 3, "images/american/praseodymium.png", 59, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t61", 3, "images/american/neodymium.png", 60, "american", "false");
  createEle("aElements1", "ame1t62", 3, "images/american/promethium.png", 61, "american", "false");
  createEle("aElements1", "ame1t63", 3, "images/american/samarium.png", 62, "american", "false");
  createEle("aElements1", "ame1t64", 3, "images/american/europium.png", 63, "american", "false");
  createEle("aElements1", "ame1t65", 3, "images/american/gadolinium.png", 64, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t66", 3, "images/american/terbium.png", 65, "american", "false");
  createEle("aElements1", "ame1t67", 3, "images/american/dysprosium.png", 66, "american", "false");
  createEle("aElements1", "ame1t68", 3, "images/american/holmium.png", 67, "american", "false");
  createEle("aElements1", "ame1t69", 3, "images/american/erbium.png", 68, "american", "false");
  createEle("aElements1", "ame1t70", 3, "images/american/thulium.png", 69, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t71", 3, "images/american/ytterbium.png", 70, "american", "false");
  createEle("aElements1", "ame1t72", 3, "images/american/lutetium.png", 71, "american", "false");
  createEle("aElements1", "ame1t73", 3, "images/american/hafnium.png", 72, "american", "false");
  createEle("aElements1", "ame1t74", 3, "images/american/tantalum.png", 73, "american", "false");
  createEle("aElements1", "ame1t75", 3, "images/american/tungsten.png", 74, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t76", 3, "images/american/rhenium.png", 75, "american", "false");
  createEle("aElements1", "ame1t77", 3, "images/american/osmium.png", 76, "american", "false");
  createEle("aElements1", "ame1t78", 3, "images/american/iridium.png", 77, "american", "false");
  createEle("aElements1", "ame1t79", 3, "images/american/platinum.png", 78, "american", "false");
  createEle("aElements1", "ame1t80", 3, "images/american/gold.png", 79, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t81", 3, "images/american/mercury.png", 80, "american", "false");
  createEle("aElements1", "ame1t82", 3, "images/american/thallium.png", 81, "american", "false");
  createEle("aElements1", "ame1t83", 3, "images/american/lead.png", 82, "american", "false");
  createEle("aElements1", "ame1t84", 3, "images/american/bismuth.png", 83, "american", "false");
  createEle("aElements1", "ame1t85", 3, "images/american/polonium.png", 84, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t86", 3, "images/american/astatine.png", 85, "american", "false");
  createEle("aElements1", "ame1t87", 3, "images/american/radon.png", 86, "american", "false");
  createEle("aElements1", "ame1t88", 3, "images/american/francium.png", 87, "american", "false");
  createEle("aElements1", "ame1t89", 3, "images/american/radium.png", 88, "american", "false");
  createEle("aElements1", "ame1t90", 3, "images/american/actinium.png", 89, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t91", 3, "images/american/thorium.png", 90, "american", "false");
  createEle("aElements1", "ame1t92", 3, "images/american/protactinium.png", 91, "american", "false");
  createEle("aElements1", "ame1t93", 3, "images/american/uranium.png", 92, "american", "false");
  createEle("aElements1", "ame1t94", 3, "images/american/neptunium.png", 93, "american", "false");
  createEle("aElements1", "ame1t95", 3, "images/american/plutonium.png", 94, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t96", 3, "images/american/americium.png", 95, "american", "false");
  createEle("aElements1", "ame1t97", 3, "images/american/curium.png", 96, "american", "false");
  createEle("aElements1", "ame1t98", 3, "images/american/berkelium.png", 97, "american", "false");
  createEle("aElements1", "ame1t99", 3, "images/american/californium.png", 98, "american", "false");
  createEle("aElements1", "ame1t100", 3, "images/american/einsteinium.png", 99, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t101", 3, "images/american/fermium.png", 100, "american", "false");
  createEle("aElements1", "ame1t102", 3, "images/american/mendelevium.png", 101, "american", "false");
  createEle("aElements1", "ame1t103", 3, "images/american/nobelium.png", 102, "american", "false");
  createEle("aElements1", "ame1t104", 3, "images/american/lawrencium.png", 103, "american", "false");
  createEle("aElements1", "ame1t105", 3, "images/american/rutherfordium.png", 104, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t106", 3, "images/american/dubnium.png", 105, "american", "false");
  createEle("aElements1", "ame1t107", 3, "images/american/seaborgium.png", 106, "american", "false");
  createEle("aElements1", "ame1t108", 3, "images/american/bohrium.png", 107, "american", "false");
  createEle("aElements1", "ame1t109", 3, "images/american/hassium.png", 108, "american", "false");
  createEle("aElements1", "ame1t110", 3, "images/american/meitnerium.png", 109, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t111", 3, "images/american/darmstadtium.png", 110, "american", "false");
  createEle("aElements1", "ame1t112", 3, "images/american/roentgenium.png", 111, "american", "false");
  createEle("aElements1", "ame1t113", 3, "images/american/copernicium.png", 112, "american", "false");
  createEle("aElements1", "ame1t114", 3, "images/american/nihonium.png", 113, "american", "false");
  createEle("aElements1", "ame1t115", 3, "images/american/flerovium.png", 114, "american", "false");
  createBre("aElements1");
  createEle("aElements1", "ame1t116", 3, "images/american/moscovium.png", 115, "american", "false");
  createEle("aElements1", "ame1t117", 3, "images/american/livermorium.png", 116, "american", "false");
  createEle("aElements1", "ame1t118", 3, "images/american/tennessine.png", 117, "american", "false");
  createEle("aElements1", "ame1t119", 3, "images/american/oganesson.png", 118, "american", "false");

  //Second american elements slot.
  createEle("aElements2", "ame2t1", 4, "images/blank.png", 0, "greek", "true");
  createEle("aElements2", "ame2t2", 4, "images/american/hydrogen.png", 1, "american", "false");
  createEle("aElements2", "ame2t3", 4, "images/american/helium.png", 2, "american", "false");
  createEle("aElements2", "ame2t4", 4, "images/american/lithium.png", 3, "american", "false");
  createEle("aElements2", "ame2t5", 4, "images/american/beryllium.png", 4, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t6", 4, "images/american/boron.png", 5, "american", "false");
  createEle("aElements2", "ame2t7", 4, "images/american/carbon.png", 6, "american", "false");
  createEle("aElements2", "ame2t8", 4, "images/american/nitrogen.png", 7, "american", "false");
  createEle("aElements2", "ame2t9", 4, "images/american/oxygen.png", 8, "american", "false");
  createEle("aElements2", "ame2t10", 4, "images/american/fluorine.png", 9, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t11", 4, "images/american/neon.png", 10, "american", "false");
  createEle("aElements2", "ame2t12", 4, "images/american/sodium.png", 11, "american", "false");
  createEle("aElements2", "ame2t13", 4, "images/american/magnesium.png", 12, "american", "false");
  createEle("aElements2", "ame2t14", 4, "images/american/aluminium.png", 13, "american", "false");
  createEle("aElements2", "ame2t15", 4, "images/american/silocon.png", 14, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t16", 4, "images/american/phosphorus.png", 15, "american", "false");
  createEle("aElements2", "ame2t17", 4, "images/american/sulfur.png", 16, "american", "false");
  createEle("aElements2", "ame2t18", 4, "images/american/chlorine.png", 17, "american", "false");
  createEle("aElements2", "ame2t19", 4, "images/american/argon.png", 18, "american", "false");
  createEle("aElements2", "ame2t20", 4, "images/american/potassium.png", 19, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t21", 4, "images/american/calcium.png", 20, "american", "false");
  createEle("aElements2", "ame2t22", 4, "images/american/scandium.png", 21, "american", "false");
  createEle("aElements2", "ame2t23", 4, "images/american/titanium.png", 22, "american", "false");
  createEle("aElements2", "ame2t24", 4, "images/american/vanadium.png", 23, "american", "false");
  createEle("aElements2", "ame2t25", 4, "images/american/chromium.png", 24, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t26", 4, "images/american/manganese.png", 25, "american", "false");
  createEle("aElements2", "ame2t27", 4, "images/american/iron.png", 26, "american", "false");
  createEle("aElements2", "ame2t28", 4, "images/american/cobalt.png", 27, "american", "false");
  createEle("aElements2", "ame2t29", 4, "images/american/nickel.png", 28, "american", "false");
  createEle("aElements2", "ame2t30", 4, "images/american/copper.png", 29, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t31", 4, "images/american/zinc.png", 30, "american", "false");
  createEle("aElements2", "ame2t32", 4, "images/american/gallium.png", 31, "american", "false");
  createEle("aElements2", "ame2t33", 4, "images/american/germanium.png", 32, "american", "false");
  createEle("aElements2", "ame2t34", 4, "images/american/arsenic.png", 33, "american", "false");
  createEle("aElements2", "ame2t35", 4, "images/american/selenium.png", 34, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t36", 4, "images/american/bromine.png", 35, "american", "false");
  createEle("aElements2", "ame2t37", 4, "images/american/krypton.png", 36, "american", "false");
  createEle("aElements2", "ame2t38", 4, "images/american/rubidium.png", 37, "american", "false");
  createEle("aElements2", "ame2t39", 4, "images/american/strontium.png", 38, "american", "false");
  createEle("aElements2", "ame2t40", 4, "images/american/yttrium.png", 39, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t41", 4, "images/american/zirconium.png", 40, "american", "false");
  createEle("aElements2", "ame2t42", 4, "images/american/niobium.png", 41, "american", "false");
  createEle("aElements2", "ame2t43", 4, "images/american/molybdenium.png", 42, "american", "false");
  createEle("aElements2", "ame2t44", 4, "images/american/technetium.png", 43, "american", "false");
  createEle("aElements2", "ame2t45", 4, "images/american/ruthenium.png", 44, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t46", 4, "images/american/rhodium.png", 45, "american", "false");
  createEle("aElements2", "ame2t47", 4, "images/american/palladium.png", 46, "american", "false");
  createEle("aElements2", "ame2t48", 4, "images/american/silver.png", 47, "american", "false");
  createEle("aElements2", "ame2t49", 4, "images/american/cadmium.png", 48, "american", "false");
  createEle("aElements2", "ame2t50", 4, "images/american/indium.png", 49, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t51", 4, "images/american/tin.png", 50, "american", "false");
  createEle("aElements2", "ame2t52", 4, "images/american/antimony.png", 51, "american", "false");
  createEle("aElements2", "ame2t53", 4, "images/american/tellurium.png", 52, "american", "false");
  createEle("aElements2", "ame2t54", 4, "images/american/iodine.png", 53, "american", "false");
  createEle("aElements2", "ame2t55", 4, "images/american/xenon.png", 54, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t56", 4, "images/american/caesium.png", 55, "american", "false");
  createEle("aElements2", "ame2t57", 4, "images/american/barium.png", 56, "american", "false");
  createEle("aElements2", "ame2t58", 4, "images/american/lanthanium.png", 57, "american", "false");
  createEle("aElements2", "ame2t59", 4, "images/american/cerium.png", 58, "american", "false");
  createEle("aElements2", "ame2t60", 4, "images/american/praseodymium.png", 59, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t61", 4, "images/american/neodymium.png", 60, "american", "false");
  createEle("aElements2", "ame2t62", 4, "images/american/promethium.png", 61, "american", "false");
  createEle("aElements2", "ame2t63", 4, "images/american/samarium.png", 62, "american", "false");
  createEle("aElements2", "ame2t64", 4, "images/american/europium.png", 63, "american", "false");
  createEle("aElements2", "ame2t65", 4, "images/american/gadolinium.png", 64, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t66", 4, "images/american/terbium.png", 65, "american", "false");
  createEle("aElements2", "ame2t67", 4, "images/american/dysprosium.png", 66, "american", "false");
  createEle("aElements2", "ame2t68", 4, "images/american/holmium.png", 67, "american", "false");
  createEle("aElements2", "ame2t69", 4, "images/american/erbium.png", 68, "american", "false");
  createEle("aElements2", "ame2t70", 4, "images/american/thulium.png", 69, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t71", 4, "images/american/ytterbium.png", 70, "american", "false");
  createEle("aElements2", "ame2t72", 4, "images/american/lutetium.png", 71, "american", "false");
  createEle("aElements2", "ame2t73", 4, "images/american/hafnium.png", 72, "american", "false");
  createEle("aElements2", "ame2t74", 4, "images/american/tantalum.png", 73, "american", "false");
  createEle("aElements2", "ame2t75", 4, "images/american/tungsten.png", 74, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t76", 4, "images/american/rhenium.png", 75, "american", "false");
  createEle("aElements2", "ame2t77", 4, "images/american/osmium.png", 76, "american", "false");
  createEle("aElements2", "ame2t78", 4, "images/american/iridium.png", 77, "american", "false");
  createEle("aElements2", "ame2t79", 4, "images/american/platinum.png", 78, "american", "false");
  createEle("aElements2", "ame2t80", 4, "images/american/gold.png", 79, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t81", 4, "images/american/mercury.png", 80, "american", "false");
  createEle("aElements2", "ame2t82", 4, "images/american/thallium.png", 81, "american", "false");
  createEle("aElements2", "ame2t83", 4, "images/american/lead.png", 82, "american", "false");
  createEle("aElements2", "ame2t84", 4, "images/american/bismuth.png", 83, "american", "false");
  createEle("aElements2", "ame2t85", 4, "images/american/polonium.png", 84, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t86", 4, "images/american/astatine.png", 85, "american", "false");
  createEle("aElements2", "ame2t87", 4, "images/american/radon.png", 86, "american", "false");
  createEle("aElements2", "ame2t88", 4, "images/american/francium.png", 87, "american", "false");
  createEle("aElements2", "ame2t89", 4, "images/american/radium.png", 88, "american", "false");
  createEle("aElements2", "ame2t90", 4, "images/american/actinium.png", 89, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t91", 4, "images/american/thorium.png", 90, "american", "false");
  createEle("aElements2", "ame2t92", 4, "images/american/protactinium.png", 91, "american", "false");
  createEle("aElements2", "ame2t93", 4, "images/american/uranium.png", 92, "american", "false");
  createEle("aElements2", "ame2t94", 4, "images/american/neptunium.png", 93, "american", "false");
  createEle("aElements2", "ame2t95", 4, "images/american/plutonium.png", 94, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t96", 4, "images/american/americium.png", 95, "american", "false");
  createEle("aElements2", "ame2t97", 4, "images/american/curium.png", 96, "american", "false");
  createEle("aElements2", "ame2t98", 4, "images/american/berkelium.png", 97, "american", "false");
  createEle("aElements2", "ame2t99", 4, "images/american/californium.png", 98, "american", "false");
  createEle("aElements2", "ame2t100", 4, "images/american/einsteinium.png", 99, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t101", 4, "images/american/fermium.png", 100, "american", "false");
  createEle("aElements2", "ame2t102", 4, "images/american/mendelevium.png", 101, "american", "false");
  createEle("aElements2", "ame2t103", 4, "images/american/nobelium.png", 102, "american", "false");
  createEle("aElements2", "ame2t104", 4, "images/american/lawrencium.png", 103, "american", "false");
  createEle("aElements2", "ame2t105", 4, "images/american/rutherfordium.png", 104, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t106", 4, "images/american/dubnium.png", 105, "american", "false");
  createEle("aElements2", "ame2t107", 4, "images/american/seaborgium.png", 106, "american", "false");
  createEle("aElements2", "ame2t108", 4, "images/american/bohrium.png", 107, "american", "false");
  createEle("aElements2", "ame2t109", 4, "images/american/hassium.png", 108, "american", "false");
  createEle("aElements2", "ame2t110", 4, "images/american/meitnerium.png", 109, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t111", 4, "images/american/darmstadtium.png", 110, "american", "false");
  createEle("aElements2", "ame2t112", 4, "images/american/roentgenium.png", 111, "american", "false");
  createEle("aElements2", "ame2t113", 4, "images/american/copernicium.png", 112, "american", "false");
  createEle("aElements2", "ame2t114", 4, "images/american/nihonium.png", 113, "american", "false");
  createEle("aElements2", "ame2t115", 4, "images/american/flerovium.png", 114, "american", "false");
  createBre("aElements2");
  createEle("aElements2", "ame2t116", 4, "images/american/moscovium.png", 115, "american", "false");
  createEle("aElements2", "ame2t117", 4, "images/american/livermorium.png", 116, "american", "false");
  createEle("aElements2", "ame2t118", 4, "images/american/tennessine.png", 117, "american", "false");
  createEle("aElements2", "ame2t119", 4, "images/american/oganesson.png", 118, "american", "false");
}
